name: Lint
on:
  # Trigger the workflow on push or pull request
  # for the main branch only
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # name of the job
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest
    # define the steps
    steps:
      # clone and checkout the master branch of our repository that Actions can access.
      - 
        name: Check out Git Repository
        uses: actions/checkout@v2

      - 
        name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - 
        name: Install Python dependencies
        run: pip install flake8 black
      
      - 
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.5.0
     
      -
        name: Build and push Docker images
        uses: docker/bake-action@main
        with: 
          push: true
        
        
